package com.ecommerce.repositories.inheritance4;
// default package
// Generated Mar 31, 2022, 2:27:18 PM by Hibernate Tools 6.0.0.Beta2


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Student generated by hbm2java
 */

@Entity
@Table(name="student"
    ,catalog="inheritance1"
)
public class Student extends Person   {


 
  private String department;

    public Student() {
    }

    public Student(String firstName, String lastName ,String department) {
       this.department = department;
       this.firstName=firstName;
       this.lastName=lastName;
    }
 
    @Column(name="department", nullable=false, length=45)
    public String getDepartment() {
        return this.department;
    }
    
    public void setDepartment(String department) {
        this.department = department;
    }




}


