package com.ecommerce.repositories.inheritance2;
// default package
// Generated Mar 31, 2022, 1:40:16 PM by Hibernate Tools 6.0.0.Beta2


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.Table;

/**
 * Person generated by hbm2java
 */
@Entity
@Table(name="person",catalog="inheritance1")
@Inheritance(strategy = InheritanceType.TABLE_PER_CLASS)
public class Person  implements java.io.Serializable {


     protected Integer id;
     protected String firstName;
     protected String lastName;

    public Person() {
    }

    public Person(String firstName, String lastName) {
       this.firstName = firstName;
       this.lastName = lastName;
    }
   
    @Id
    @GeneratedValue(strategy=GenerationType.TABLE)
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }


    @Column(name="first_name", nullable=false, length=50)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="last_name", nullable=false, length=50)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }




}


