//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.07 at 12:50:54 PM EET 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "https://jets.iti.gov.eg/xml/book", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package gov.iti.jets.dto;
