package com.ecommerce.repositories.inheritance1;
// default package
// Generated Mar 31, 2022, 12:59:11 PM by Hibernate Tools 6.0.0.Beta2


import javax.persistence.Column;
import javax.persistence.MappedSuperclass;

/**
 * Person generated by hbm2java
 */
 
@MappedSuperclass
public class Person  implements java.io.Serializable {


     protected String firstName;
     protected String lastName;

    public Person() {
    }

    public Person(String firstName, String lastName) {
       this.firstName = firstName;
       this.lastName = lastName;
    }

    
    @Column(name="first_name", nullable=false, length=50)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="last_name", nullable=false, length=50)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }




}


