POST http://localhost:9090/soapwithjpacreditcard/ws/testing HTTP/1.1
Content-Type: text/xml

<?xml version="1.0"?>
<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:jets="http://services.backend.iti.gov/">

    <soap:Body>
        <jets:showAccountDetails>
            <arg0>Hany</arg0>
            <arg1>40</arg1>
         </jets:showAccountDetails>
    </soap:Body>

</soap:Envelope>

###

POST http://localhost:9090/soapwithjpacreditcard/ws/testing HTTP/1.1
Content-Type: text/xml

<?xml version="1.0"?>
<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:jets="http://services.backend.iti.gov/">

    <soap:Body>
        <jets:registerEmployee>
            <arg0>
                <firstName>Hany</firstName>
                <password>40</password>
                <accountEntity>
                    <accountLimit>15000</accountLimit>
                </accountEntity>
            </arg0>
        </jets:registerEmployee>
    </soap:Body>

</soap:Envelope>

###

POST http://localhost:9090/soapwithjpacreditcard/ws/testing HTTP/1.1
Content-Type: text/xml

<?xml version="1.0"?>
<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:jets="http://services.backend.iti.gov/">

    <soap:Body>
        <jets:transferAmount>
            <arg0>HASHEM</arg0>

            <arg1>24</arg1>

            <arg2>ASHRAF</arg2>

            <arg3>1000.00</arg3>

        </jets:transferAmount>
    </soap:Body>

</soap:Envelope>

###

POST http://localhost:9090/soapwithjpacreditcard/ws/testing HTTP/1.1
Content-Type: text/xml

<?xml version="1.0"?>
<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:jets="http://services.backend.iti.gov/">

    <soap:Body>
        <jets:testException>


        </jets:testException>
    </soap:Body>

</soap:Envelope>

###